title: saxomode Demos
author: saxomode contributors
logo: null
only_build_toc_files: true
repository:
  url: https://github.com/ComputationalPhysiology/MAD-SSA.git # Online location of your book
  branch: main
html:
  use_issues_button: true
  use_repository_button: true
logo: saxomode-book/logo.png